databases:
  - name: budgetbox-db
    databaseName: budgetbox
    user: budgetbox_user
    plan: free

services:
  - type: web
    name: budgetbox-api
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budgetbox-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
